<?xml version="1.0" encoding="utf-8"?><Database Name="SalonManagementSystem" Class="CustomerDetailsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-U2TIPAG;Initial Catalog=SalonManagementSystem;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SalonManagementSystemConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Tbl_Customer_Details" Member="Tbl_Customer_Details">
    <Type Name="Tbl_Customer_Detail">
      <Column Name="cust_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="cust_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="cust_city" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="cust_gender" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="cust_email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="cust_contact" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="date_added" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="active_status" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>