<?xml version="1.0" encoding="utf-8"?><Database Name="sms" Class="ServicesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Tbl_Services" Member="Tbl_Services">
    <Type Name="Tbl_Services">
      <Column Name="service_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="service_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="service_time_span" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="service_price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>